<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.master" AutoEventWireup="true" CodeFile="restrans.aspx.cs" Inherits="restrans" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
  <!---table---->
    <div class="container"><br /><br />
        <div class="panel panel-default" style="overflow:auto;">
              <!-- Default panel contents -->
            <div class="panel-heading">All Data<br />

                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"
                     AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
                     DataKeyNames="tId" DataSourceID="SqlDataSource2" CellPadding="4" ForeColor="#333333" GridLines="None">
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />

                    <Columns>
                        <asp:BoundField DataField="tId" HeaderText="tId" InsertVisible="False" ReadOnly="True" SortExpression="tId" />
                    
                        <asp:BoundField DataField="location" HeaderText="location" SortExpression="location" />
                       
                        <asp:BoundField DataField="description" HeaderText="description" SortExpression="description" />
                    </Columns>

                    <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                    <SortedAscendingHeaderStyle BackColor="#506C8C" />
                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                    <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                </asp:GridView>

                <asp:SqlDataSource ID="SqlDataSource2" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:UserConnectionString1 %>"
                     DeleteCommand=" DELETE FROM [transportimage] WHERE [tId] = @tId ; DELETE FROM [transport] WHERE [tId] = @tId" 
                    InsertCommand="INSERT INTO [transport ( [location],  [description]) VALUES (@location, @description)"
                     SelectCommand="SELECT * FROM [transport]"
                     UpdateCommand="UPDATE [transport] SET [location] = @location, [description] = @description WHERE [tId] = @tId">
                  
                      <DeleteParameters>
                        <asp:Parameter Name="tId" Type="Int64" />
                    </DeleteParameters>

                    <InsertParameters>
                        
                        <asp:Parameter Name="location" Type="String" />
                       
                        <asp:Parameter Name="description" Type="String" />
                    </InsertParameters>
                    <UpdateParameters>
                       
                        <asp:Parameter Name="location" Type="String" />
                     
                        <asp:Parameter Name="description" Type="String" />
                        <asp:Parameter Name="tId" Type="Int64" />
                    </UpdateParameters>
                </asp:SqlDataSource>
                
              </div>
          </div>
              <!-- Table -->
             
                        
                    
        </div>
        <!---table end--->


</asp:Content>

